name: Docker push
on:
  push:
    branches:
    - master
    - CI
    tags:
      - v1.*
  pull_request:
    branches-ignore:
    - release

jobs:
  build:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
  docker-build:
    name: build-docker
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: docker-build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/dtp-training
        tag_with_ref: true
        push: true
